# Generated by Django 6.0.8 on 2026-09-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_alert_options_remove_alert_metric_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='metric_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('danger', 'Danger'), ('success', 'Success')], default='warning', max_length=10),
        ),
    ]
